twig:
    paths:
        '%kernel.project_dir%/src/ModuloCore/templates': ~
        '%kernel.project_dir%/src/ModuloExplorador/templates': ~
        '%kernel.project_dir%/src/ModuloChat/templates': ModuloChat
        # '%kernel.project_dir%/src/ModuloTest/templates': ~