version: '3.8'

services:
  mercure:
    image: dunglas/mercure
    container_name: symfony_mercure
    restart: unless-stopped
    environment:
      # Habilitar modo debug
      - DEBUG=1
      # Clave utilizada para firmar los JWT
      - JWT_KEY=${MERCURE_JWT_SECRET:-!ChangeThisToASecureRandomString!}
      # URL del servidor Mercure
      - MERCURE_PUBLISHER_JWT_KEY=${MERCURE_JWT_SECRET:-!ChangeThisToASecureRandomString!}
      - MERCURE_SUBSCRIBER_JWT_KEY=${MERCURE_JWT_SECRET:-!ChangeThisToASecureRandomString!}
      # Permitir todos los orígenes
      - CORS_ALLOWED_ORIGINS=*
      # Permitir publicar desde cualquier origen
      - PUBLISH_ALLOWED_ORIGINS=*
      # Habilitar autenticación anónima para suscripciones
      - ALLOW_ANONYMOUS=1
      # Opcional: Configurar usuario administrador
      - MERCURE_EXTRA_DIRECTIVES=cors_allowed_origins *
    ports:
      - "9090:80"
    volumes:
      - mercure_data:/data

networks:
  default:
    driver: bridge

volumes:
  mercure_data: {}