# Crea este archivo como C:\Users\ruptur\Desktop\exnet-core-31-03-2025-v2\exnet-core\docker-compose.yml
services:
  php:
    build: .
    volumes:
      - .:/var/www/html
    networks:
      - exnet_network

  nginx:
    image: nginx:stable-alpine
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./wg0.conf:/etc/wireguard/wg0.conf 
    depends_on:
      - php
    networks:
      - exnet_network

networks:
  exnet_network:
    driver: bridge