version: '3'

services:
  php:
    build:
      context: .
    image: exnet-core_php:dev
    volumes:
      - .:/var/www/html
    networks:
      - exnet_network
    environment:
      - PHP_MEMORY_LIMIT=256M
      - PHP_MAX_EXECUTION_TIME=60
      - APP_ENV=dev

  nginx:
    image: nginx:stable-alpine
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      - exnet_network

networks:
  exnet_network:
    driver: bridge