modulo_core_controllers:
    resource:
        path: ../src/ModuloCore/Controller/
        namespace: App\ModuloCore\Controller
    type: attribute
# ----------- modulochat -------
modulo_chat_controllers:
    resource:
        path: ../src/ModuloChat/Controller/
        namespace: App\ModuloChat\Controller
    type: attribute
# ----------- modulochat -------