modulo_core_controllers:
    resource:
        path: ../src/ModuloCore/Controller/
        namespace: App\ModuloCore\Controller
    type: attribute

modulo_chat_controllers:
    resource:
        path: ../src/ModuloChat/Controller/
        namespace: App\ModuloChat\Controller
    type: attribute

modulo_musica_controllers:
    resource:
        path: ../src/ModuloMusica/Controller/
        namespace: App\ModuloMusica\Controller
    type: attribute

modulo_explorador_controllers:
    resource:
        path: ../src/ModuloExplorador/Controller/
        namespace: App\ModuloExplorador\Controller
    type: attribute

modulo_streaming_controllers:
    resource:
        path: ../src/ModuloStreaming/Controller/
        namespace: App\ModuloStreaming\Controller
    type: attribute