modulo_core_controllers:
    resource:
        path: ../src/ModuloCore/Controller/
        namespace: App\ModuloCore\Controller
    type: attribute

# modulo_chat_controllers: DESACTIVADO
# resource:
#     path: ../src/ModuloChat/Controller/
#     namespace: App\ModuloChat\Controller
# type: attribute    
modulo_explorador_controllers:
    resource:
        path: ../src/ModuloExplorador/Controller/
        namespace: App\ModuloExplorador\Controller
    type: attribute
    
streaming_routes:
    resource: '../src/ModuloStreaming/Controller/'
    type: attribute
    prefix: /