modulo_core_controllers:
    resource:
        path: ../src/ModuloCore/Controller/
        namespace: App\ModuloCore\Controller
    type: attribute

modulo_musica_controllers:
    resource:
        path: ../src/ModuloMusica/Controller/
        namespace: App\ModuloMusica\Controller
    type: attribute