# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    websocket_url: 'https://websockettest.exnet.cloud'
    cdn_base_url: 'https://cdn.exnet.cloud'
    jwt.auth_mode: 'jwt'
    jwt.cookie_name: 'exnet_auth_jwt'
    jwt.token_lifetime: 86400
    app.backup_dir: '%kernel.project_dir%/var/backups'
    API_URL: '%env(API_URL)%'
    KEYCLOAK_REALM: '%env(KEYCLOAK_REALM)%'
    KEYCLOAK_URL: '%env(KEYCLOAK_URL)%'
    videos_directory: '%kernel.project_dir%/public/uploads/videos'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    #START -----------------------------------------------------  ModuloCore -------------------------------------------------------------------------
    App\ModuloCore\Controller\:
        resource: '../src/ModuloCore/Controller'
        tags: ['controller.service_arguments']

    App\ModuloCore\EventSubscriber\MenuSubscriber:
        tags: ['kernel.event_subscriber']
                  
    App\ModuloCore\Command\SetupCommand:
        autowire: true
        autoconfigure: true
        arguments:
            $httpClient: '@http_client'

    App\ModuloCore\Service\IpAuthService:
        arguments:
            $entityManager: '@doctrine.orm.entity_manager'
            $requestStack: '@request_stack'

    App\ModuloCore\Service\JwtAuthService:
        arguments:
            $appSecret: '%kernel.secret%'

    App\ModuloCore\Service\BackupService:
        arguments:
            $backupDir: '%app.backup_dir%'
            $projectDir: '%kernel.project_dir%'
    
    App\ModuloCore\EventSubscriber\JwtAuthSubscriber:
        tags:
            - { name: kernel.event_subscriber }
    
    App\ModuloCore\Service\CdnService:
        arguments:
            $httpClient: '@http_client'
            $entityManager: '@doctrine.orm.entity_manager'
            $parameterBag: '@parameter_bag'

    #END ------------------------------------------------------- ModuloCore ---------------------------------------------------------------------------        
